runtime: nodejs16
env: standard
instance_class: F1
handlers:
  - url: /build/(.*\..+)$
    static_files: public/build/\1
    upload: public/build/(.*\..+)$ #Catch all handler to index.html
  - url: /.*
    static_files: public/index.html
    upload: public/index.html
    secure: always
    redirect_http_response_code: 301
env_variables:
  BUCKET_NAME: mintdapp
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: mintdapp@appspot.gserviceaccount.com
